config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
resources :images

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord

    mount_uploader :picture, PictureUploader

    validates :description, presence:true

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :email, presence:true
      has_many :images  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery whith: :exception
    before_action :configure_devise_params, if: :devise_controller?
    
    def configure_devise_params
       devise_parameter_sanitizer.permit(:sign_up) do |user|
        user.permit(:name, :email, :password, :password_confirmation)
        end 
    end
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
before_action :set_image, only: [:show, :edit, :update, :destroy]
    def index
 @images = Image.where user_id: current_user.id

    end

   def show
    
   end 

   def edit
    
   end
   def update
   
    @image.update images_params
    redirect_to @image
    end
    
    def new
        @image = Image.new 
    end

    def create
        @image =current_user.images.new  images_params
 #      @image = Image.new images_params
       if @image.save
        redirect_to @image
       end
       render :new
    end


    def destroy
      @image = Image.find params[:id]
      @image.destroy
      redirect_to @image

    end


 private
    def images_params
        params.require(:image).permit(:description, :picture)
    end
    
    def set_image
        @image = Image.find params[:id]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <h2> Bienvenido <%= current_user.name %> </h1>
<% else %>
  <h2> BOOKGRAM </h2>
<% end %> 

app/views/images/_form.html.erb
<div class="form-group">
   <%= form_for @image do |f| %>
     <%= f.label :description%> <br>
     <%= f.text_field :description, class: 'form-control' %>
     <%- if @image.errors[:descriptions].any? %>
     <span class="badge badge-pell badge-pell">
     <%= @image.errors[:description].first %>
     </span>
     <% end %><s 
     <br>
     <%= f.label :picture%> <br>
     <%= f.file_field :picture %>
     <br>
     <%= f.submit 'Enviar', :class => 'btb btn-primary' %>
    <% end %>
<div>
<%- if @image.errors.any? %>
   <div class="alert alert-danger">
    <h4 classs="alert-heading">  :C </h4>
    <p> ha ocurrido un error </p>
   </div>
<% end %>

app/views/images/_image.html.erb
<div class="col-sm-3">
   <figure class="figure">
   <%= image_tag image.picture.thumb.url, class:'figure-img img-fluid rounded'%>
   
       <figcaption class="figure-caption"> <%= image.description %>
          <%= link_to 'Editar', edit_image_path(image) %>
           <%= link_to 'Eliminar', image, method: :delete, data: { confirm: 'sure?'} %>
        </figcaption>
   </figure>
</div>

app/views/images/edit.html.erb
<p> edit</p>

<%= render 'form' %>

app/views/images/index.html.erb
<div class="container">
  <div class="row">
  <%= render @images %>
  </div>
  </div>


    

app/views/images/new.html.erb
<div class="container">
  <div class="row">
     <p> nuevo romulario</p>
     <%= render 'form' %>
    </div>     
 </div>

app/views/images/show.html.erb
<%= image_tag @image.picture.thumb.url, class:'figure-img img-fluid rounded'%>

<%= @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <style>
body {background-color: powderblue;}
</style>
</head>
<body>
<ul class="nav justify-content-end">
    <%- if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
       </li>
       <% else %>
         <li class="nav-item">
         <%= link_to 'Iniciar', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Registar', new_user_registration_path, class: "nav-link" %>
          </li>

    <% end %>   
</ul>


    <div class= "container">
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
     <%= yield %>
     </div>
   
  </body>
</html>